name = "TriangularMatrices"
uuid = "c1b978d4-7f77-4b0f-b75a-d16d5727af9b"
authors = ["azzaare (jean-François BAFFIER)"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
